#!/usr/bin/env bash

export DISPLAY=:0

# Set phone display resolution
adb shell wm density 200
adb shell settings put system font_scale 1.3
adb shell wm size 720x1280

sleep 0.5

# Start screen mirror
pkill scrcpy
scrcpy --video-codec=h264 --max-size=1024 --max-fps=30 --no-audio --orientation=flip180 --disable-screensaver --no-control --video-bit-rate=1M --fullscreen
